export { default as History } from './History'
export { default as Home } from './Home'
export { default as Meaning } from './Meaning'
export { default as Profile } from './Profile'
export { default as Saved } from './Saved'
export { default as Search } from './Search'
